# Course/Page specific config options
subbrand: ANU CECS
title: ANU CECS Template Page
description: A template webpage for the new ANU Jekyll web theme.
baseurl: ""
url: ""
date_format: "%b %-d, %Y"
permalink: pretty
future: true

# This allows you to set default values for pages in specific categories.
# I.e. the 'layout' option for all pages (path = "") is set to 'default' (the file named 'default' in _layouts in the jekyll-theme-anu repo)
#      and the default banner image is set by the 'image' tag path.
# And for all pages under "_resources", we override the default layout with a custom theme declared in our local _layouts that is a
# duplicate of the default layout, except without the deep-linking functionality of mousing over headings.
defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/images/ANU_Hanna_Neumann_Building_by_photographer_Rodrigo_Vargas.jpg
      show_anchor_headings: true
  - scope:
      path: "index.md"
    values:
      layout: use-liquid-boxes

# Pick which theme we want to use. All new jekyll ANU webpages will use this jekyll-theme-anu theme.
theme: jekyll-theme-anu

# Values that can be accessed by pages, i.e. a 'contact' option in the footer of every page.
contacts:
  responsible_officer:
    name: School Director
    email: director.comp@anu.edu.au
  page_contact:
    name: CECS Jekyll Web Support
    email: e1d2d6ca.ANU365.onmicrosoft.com@apac.teams.ms

# The config options for the top bar menus. 
# Add and remove options as you please, as long as the options you add have a valid 'page:' value, otherwise you will not be able to build the page.
# This layout is purely an example and is meant to be adapted to your specific webpage needs. This sample loosely follows the needs of a course page.
menu:
  - name: About
    page: _about/index.md
    children:
      - name: Contact
        page: _about/contact.md
  - name: Lectures
    page: _lectures/index.md
  - name: Labs
    page: _labs/index.md
    children:
      - name: Lab 1
        page: _labs/lab01.md
      - name: Lab 2
        page: _labs/lab02.md
      # ... and so on
  - name: Assessments
    page: _assessments/index.md
    # you could also list the children of the assessments group here, or link them in the assessments landing page.
  - name: Resources
    page: _resources/index.md
  - name: Help
    page: 03-getting-help.md
# A lot of choices here are up to your specific style needs.

# Specify to jekyll what directories you want included in your website when it builds.
collections:
  about:
    output: true
  lectures:
    output: true
  labs:
    output: true
  assessments:
    output: true
  resources:
    output: true
  

# Jekyll specific options, should be able to just leave these as they are.
markdown: kramdown
highlighter: none

jekyll_proofer: warn

autoprefixer:
  browsers:
    - last 2 versions
  # uncomment out line below to turn off autoprefixing and speed up local build for development
  # only_production: true

# Sample values that can be assigned to the 'socials' list that pages can access and use. 
# These socials links are used in the footers of pages under the 'Acknowledgement of Country', and with the other 'contact' links.
# socials:
#   twitter: 
#   facebook: 
#   insta: 
#   youtube: 
#   linkedin: 
#   wechat: 

# You may add your own YAML tags to this _config file if you want too. An example may be some important links that would be referenced many times
# throughout your webpage. I.e. a link to the CECS Jekyll web support teams channel:
jekyll-support-link: https://teams.microsoft.com/l/team/19%3aIcnInMyxTJ26Ik8FrUs9SefrG_9seawpDu95NmKwiIE1%40thread.tacv2/conversations?groupId=dab190b1-14f2-40cf-b384-ee00c63d2019&tenantId=e37d725c-ab5c-4624-9ae5-f0533e486437
jekyll-support-email: e1d2d6ca.ANU365.onmicrosoft.com@apac.teams.ms


# Don't worry about anything listed below here.

# analytics_id: insert tracking or measurement id here

## jekyll-paginate-v2 for pagination
pagination:
  enabled: true
  collection: posts
  indexpage: index
  extension: html
  sort_field: date
  sort_reverse: true

## jekyll-paginate-v2 for auto-pages
# autopages:
#   enabled: true
#   collection: posts
#   tags:
#     enabled: true
#     permalink: /news/tag/:tag/
#     title: Tag - :tag
#     layouts:
#       - autopage_tags.html
#     slugify:
#       mode: default
#       case: true
#   collections:
#     enabled: false
#   categories:
#     enabled: false
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
