# This is a basic workflow to help you get started with Actions

name: BUILD-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # setup git keys
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Jekyll Actions
        uses: helaili/jekyll-action@2.4.0
        with:
          # The GITHUB_TOKEN secret
          token: ${{ secrets.EPIC_TOKEN }}
          keep_history: true
          target_path: /
          # The target branch name the site gets pushed to
          target_branch: master
